matchers:
  User-Agent:
    default:
      regex: .*
      vars: &default
        device_stylesheet: main.css
        stylesheet_asset_location: "/stylesheets/.css/"
        image_asset_location: "/images/"
        js_asset_location: "/javascript/"

    webkit: 
      regex: WebKit
      vars: &webkit
        <<: *default
        device_stylesheet: devices/webkit.css

    iphone: 
      regex: iPhone
      vars: &iphone
        <<: *default
        device_stylesheet: devices/iphone.css

    ipad:
      regex: iPad
      vars:
        <<: *webkit
        device_stylesheet: devices/ipad.css

    webos:
      regex: webOS
      vars:
        <<: *webkit
        device_stylesheet: devices/webos.css
        
    android:
      regex: Android
      vars:
        <<: *webkit
        device_stylesheet: devices/android.css

    blackberry:
      regex: Blackberry
      vars:
        <<: *default
        device_stylesheet: devices/blackberry.css

